//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenCell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opencell
    {
        public int ID { get; set; }
        public string radio { get; set; }
        public string mcc { get; set; }
        public string net { get; set; }
        public string area { get; set; }
        public string cell { get; set; }
        public string unit { get; set; }
        public Nullable<double> lon { get; set; }
        public Nullable<double> lat { get; set; }
        public string range { get; set; }
        public string samples { get; set; }
        public string changeable { get; set; }
        public string created { get; set; }
        public string updated { get; set; }
        public string averageSignal { get; set; }
    }
}
